language: ruby

rvm:
  - 2.2.0

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

branches:
  only:
    - master

install:
  - cd src
  - bundle install

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test