# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f0da9eb834aefc9bcaa5efaafa26629e4b8194176a14ec86ca834895d83cae43618d83ff8b2c14dbc703bdbec0a9177880329873aacbec972a1c7ee13b3d1d2

test:
  secret_key_base: 4363cf9d64f1e534f19e7a8f55bd6e2e2e0a2197020955b62b21d3c12c7b0071adc5cc8748128188abd406a04b8c828f8e0f7b2e34ab936a6c927fa5e782cd90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
